# docker-compose.yml
version: '3.8'

services:
  admin:
    container_name: admin_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200' # Перенаправление порта 80
    restart: always
